name: "Create a new release"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "NPM Package version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.release_tag }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint & Compile
        run: |
          npm run lint
          npm run compile

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
